pipeline {
    agent {
	dockerfile {
	    dir 'jenkins'
	    args '-v /tmp:/data'
	}
    }

    stages {
	stage('3rd Party Libs') {
	    steps {
		env {
		    CONAN_USER_HOME = '/data/.conan'
		}
		script {
		    sh """
			mkdir build || true
			cd build
			conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
			conan install .. --build missing
			"""
		}
	    }
	}
    }
}
