pipeline {
    agent {
	dockerfile {
	    dir 'jenkins'
	    args '-v /tmp:/data'
	}
    }

    env {
       CONAN_USER_HOME = '/data/.conan'
    }


    stages {
	stage('3rd Party Libs') {
	    steps {
		script {
		    sh """
			mkdir build || true
			cd build
			conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
			conan install .. --build missing
			"""
		}
	    }
	}
    }
}
